### ISSUE TITLE
How to handle infraspecificEpithets

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/rinse-registry-checklist#5]
As mentioned in #3, infraspecificEpithet is combined with specificEpithet in `species` in the source data. Together with the `genus`, this creates a scientific name we can submit to GBIF for parsing.

The resulting name is fine for animal names, which are written as:

    Genus specificEpithet infraspecificEpithet

but not for plant names, where the infraspecific rank has to be known and included in the scientific name

    Genus specificEpithet subsp. infraspecificEpithet
    Genus specificEpithet var. infraspecificEpithet

Since we do not have the rank of the taxa in this checklist, it is impossible to build proper scientific names for the plants. The best course of action would be:

- To write the names as `Genus specificEpithet infraspecificEpithet`, even for plants
- To not provide a `taxonRank` for (plant) infraspecific names
- To not provide a nomenclaturalCode
- To hope that the name matching at GBIF will match with something valid
- To indicate this issue in the metadata

**Comment by qgroom** [comment]
We don't have taxon rank in our specimen data either and I will find out tomorrow it GBIF can figure out the rank. I'll let you know what I find out.

**Comment by peterdesmet** [comment]
The GBIF name parser != name matching. The name parser just reads a string and tries to figure out how to parse it. It is independent from the backbone.

Also, I think the parser will only provide a specific infraspecific rank if that information is included in the name string. Compare: http://api.gbif.org/v1/parser/name?name=Sinapis%20alba%20dissecta&name=Sinapis%20alba%20var.%20dissecta

If `var.` is included in the name, the name parser will indicate rankMarker `var.`, otherwise `infrasp.`. **Not sure if this is the same result you get from rgbif?**

For infraspecific ranks, I would add the valid rank `infraspecificname` (see http://rs.gbif.org/vocabulary/gbif/rank_2015-04-24.xml)

**Comment by LienReyserhove** [comment]
I get the same result from rgbif. In this case, all these species are considered to be `infrasp`
Good suggestion to use `infraspecificname`.
