### ISSUE TITLE
Duplicates in scientific name

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/rinse-registry-checklist#8]
It appears that some taxa in the checklist appear twice :unamused: (see table bellow for a summary of all duplicated taxa). This is because:

- most duplicated species have contrasting presence information for one country (e.g. _Anchusa arvensis_). For some of these species, one record has the note "data based solely on DAISIE portal", while the other records lacks this note. In the main article, I found this:

> data based solely on DAISIE portal - taxon listed as present by the DAISIE portal but not by any of the other databases consulted; no additional portal was consulted regarding geographical distribution (also see Methods section)

So, does this mean that, in the one case, only the DAISIE portal was consulted, and in the others, all portals were consulted? Which distribution information do we use then? I see that this also affects species presence for Belgium.

- Some duplicated species are assigned to two kingdoms, i.e. _Elachista_ and _Acrophyllum dentatum_. I can find information that verifies both cases...So if this is information is in fact true, then we will get the same taxonID for both species, which is problematic.

In case of the first problem, I think it is best to contact the authors for advice. In the second problem, I'm not sure what to do. I can generate a taxonID based on the combination of phylum and scientifc name in this case? 

|phylum_division  |class            |genus       |species           |great_britain |france        |belgium       |netherlands   |environment |notes                              |scientificName              |
|:----------------|:----------------|:-----------|:-----------------|:-------------|:-------------|:-------------|:-------------|:-----------|:----------------------------------|:---------------------------|
|Angiospermae     |Eudicotyledoneae |Acrophyllum |dentatum          |present       |not confirmed |not confirmed |not confirmed |terrestrial |NA                                 |Acrophyllum dentatum        |
|Angiospermae     |Eudicotyledoneae |Anchusa     |arvensis          |present       |not confirmed |not confirmed |not confirmed |terrestrial |data based solely on DAISIE portal |Anchusa arvensis            |
|Angiospermae     |Eudicotyledoneae |Anchusa     |arvensis          |not confirmed |not confirmed |present       |not confirmed |terrestrial |NA                                 |Anchusa arvensis            |
|Angiospermae     |Monocotyledoneae |Avena       |sterilis          |present       |not confirmed |not confirmed |not confirmed |terrestrial |data based solely on DAISIE portal |Avena sterilis              |
|Angiospermae     |Monocotyledoneae |Avena       |sterilis          |not confirmed |not confirmed |present       |not confirmed |terrestrial |NA                                 |Avena sterilis              |
|Angiospermae     |Monocotyledoneae |Avena       |strigosa          |present       |present       |not confirmed |not confirmed |terrestrial |data based solely on DAISIE portal |Avena strigosa              |
|Angiospermae     |Monocotyledoneae |Avena       |strigosa          |not confirmed |not confirmed |present       |not confirmed |terrestrial |NA                                 |Avena strigosa              |
|Angiospermae     |NA               |Beta        |vulgaris          |not confirmed |present       |not confirmed |not confirmed |terrestrial |NA                                 |Beta vulgaris               |
|Angiospermae     |NA               |Beta        |vulgaris          |not confirmed |not confirmed |present       |not confirmed |terrestrial |NA                                 |Beta vulgaris               |
|Angiospermae     |NA               |Brassica    |elongata          |present       |present       |not confirmed |not confirmed |terrestrial |data based solely on DAISIE portal |Brassica elongata           |
|Angiospermae     |NA               |Brassica    |elongata          |not confirmed |not confirmed |present       |not confirmed |terrestrial |NA                                 |Brassica elongata           |
|Angiospermae     |NA               |Chenopodium |berlandieri       |present       |not confirmed |not confirmed |not confirmed |terrestrial |data based solely on DAISIE portal |Chenopodium berlandieri     |
|Angiospermae     |NA               |Chenopodium |berlandieri       |not confirmed |not confirmed |present       |not confirmed |terrestrial |NA                                 |Chenopodium berlandieri     |
|Angiospermae     |NA               |Chenopodium |strictum          |present       |not confirmed |not confirmed |not confirmed |terrestrial |data based solely on DAISIE portal |Chenopodium strictum        |
|Angiospermae     |NA               |Chenopodium |strictum          |not confirmed |not confirmed |present       |not confirmed |terrestrial |NA                                 |Chenopodium strictum        |
|Angiospermae     |Monocotyledoneae |Cynodon     |incompletus       |present       |not confirmed |not confirmed |not confirmed |terrestrial |data based solely on DAISIE portal |Cynodon incompletus         |
|Angiospermae     |Monocotyledoneae |Cynodon     |incompletus       |not confirmed |not confirmed |present       |not confirmed |terrestrial |NA                                 |Cynodon incompletus         |
|Angiospermae     |Eudicotyledoneae |Epilobium   |x novae-civitatis |present       |not confirmed |not confirmed |not confirmed |terrestrial |data based solely on DAISIE portal |Epilobium x novae-civitatis |
|Angiospermae     |Eudicotyledoneae |Epilobium   |x novae-civitatis |not confirmed |not confirmed |present       |not confirmed |terrestrial |NA                                 |Epilobium x novae-civitatis |
|Angiospermae     |NA               |Hypericum   |hircinum          |present       |not confirmed |not confirmed |not confirmed |terrestrial |data based solely on DAISIE portal |Hypericum hircinum          |
|Angiospermae     |NA               |Hypericum   |hircinum          |not confirmed |present       |not confirmed |not confirmed |terrestrial |NA                                 |Hypericum hircinum          |
|Angiospermae     |NA               |Lythrum     |junceum           |present       |not confirmed |not confirmed |not confirmed |terrestrial |data based solely on DAISIE portal |Lythrum junceum             |
|Angiospermae     |NA               |Lythrum     |junceum           |not confirmed |not confirmed |present       |not confirmed |terrestrial |NA                                 |Lythrum junceum             |
|Angiospermae     |NA               |Mentha      |x piperita        |present       |not confirmed |present       |not confirmed |terrestrial |data based solely on DAISIE portal |Mentha x piperita           |
|Angiospermae     |NA               |Mentha      |x piperita        |not confirmed |not confirmed |present       |not confirmed |terrestrial |NA                                 |Mentha x piperita           |
|Angiospermae     |Monocotyledoneae |Papaver     |atlanticum        |present       |not confirmed |present       |not confirmed |terrestrial |data based solely on DAISIE portal |Papaver atlanticum          |
|Angiospermae     |Monocotyledoneae |Papaver     |atlanticum        |present       |not confirmed |present       |present       |terrestrial |NA                                 |Papaver atlanticum          |
|Angiospermae     |NA               |Populus     |nigra             |present       |not confirmed |not confirmed |not confirmed |terrestrial |data based solely on DAISIE portal |Populus nigra               |
|Angiospermae     |NA               |Populus     |nigra             |not confirmed |not confirmed |present       |not confirmed |terrestrial |NA                                 |Populus nigra               |
|Angiospermae     |NA               |Salix       |x sepulcralis     |present       |present       |not confirmed |not confirmed |terrestrial |data based solely on DAISIE portal |Salix x sepulcralis         |
|Angiospermae     |NA               |Salix       |x sepulcralis     |not confirmed |not confirmed |present       |not confirmed |terrestrial |NA                                 |Salix x sepulcralis         |
|Arthropoda       |Insecta          |Cinara      |pini              |present       |present       |not confirmed |present       |terrestrial |NA                                 |Cinara pini                 |
|Arthropoda       |Insecta          |Cinara      |pini              |present       |not confirmed |not confirmed |not confirmed |terrestrial |NA                                 |Cinara pini                 |
|Arthropoda       |Insecta          |Elachista   |sp.               |present       |present       |present       |present       |marine      |NA                                 |Elachista sp.               |
|Bryophyta        |Eudicotyledoneae |Acrophyllum |dentatum          |present       |not confirmed |not confirmed |not confirmed |terrestrial |NA                                 |Acrophyllum dentatum        |
|Heterokontophyta |Phaeophyceae     |Elachista   |sp.               |not confirmed |not confirmed |not confirmed |present       |marine      |NA                                 |Elachista sp.               |
|Nematoda         |Adenophorea      |Xiphinema   |rivesi            |not confirmed |present       |not confirmed |not confirmed |terrestrial |NA                                 |Xiphinema rivesi            |
|Nematoda         |Adenophorea      |Xiphinema   |rivesi            |not confirmed |present       |not confirmed |not confirmed |terrestrial |NA                                 |Xiphinema rivesi            |
|Pteridophyta     |Pteridopsida     |Dicksonia   |antarctica        |present       |not confirmed |not confirmed |not confirmed |terrestrial |NA                                 |Dicksonia antarctica        |
|Pteridophyta     |Pteridopsida     |Dicksonia   |antarctica        |present       |not confirmed |not confirmed |not confirmed |terrestrial |NA                                 |Dicksonia antarctica        |

**Comment by qgroom** [comment]
Regarding the kingdoms:

_Elachista_ seems to be a hemihomonym problem, one is an algae (http://www.algaebase.org/search/genus/detail/?genus_id=c94298cee5ba4e03f&sk=0)
one is a moth (https://en.wikipedia.org/wiki/Elachista).

This paper has a useful list [http://mapress.com/j/bn/article/viewFile/bionomina.4.1.3/29](http://mapress.com/j/bn/article/viewFile/bionomina.4.1.3/29)

_Acrophyllum_ also has the same problem.
https://species.wikimedia.org/wiki/List_of_valid_homonyms

However, in this case it the homonym is not the problem it seems to be a spelling mistake.
_Achrophyllum dentatum_ is a Bryophyte in the class Bryopsida.
_Acrophyllum_ is a dicot, but there is no such thing as _Achrophyllum dentatum_.

**Comment by qgroom** [comment]
Regarding the _"data based solely on DAISIE portal"_

The provenance information is very poor on DAISIE so I don't like to use it, if I can help it.
However, it seems from the data in this table that the provenance information is even worse in RINSE.

Could we just ignore the rows that say _"data based solely on DAISIE portal"_? If you output a list of the species we might miss by doing this we could potential add them to the ad hoc list.

**Comment by timadriaens** [comment]
good idea to confront those lists and use this as inspiration for the ad hoc list but as those records are part of the RINSE register I would leave them in even if we know they are probably a copy paste from a website with little information behind. I believe these kind of decisions (_which sources from which autoritative checklists_) are typically something for the pipeline to build the unified checklist, no?

**Comment by peterdesmet** [comment]
+1 to leave them in. The register is referenced as having 6661 taxa (see [here](https://link.springer.com/article/10.1007/s10530-016-1278-z#Sec1)). Would indicate source literally as  `data based solely on DAISIE portal`, which would allow to filter them out.

Regarding the duplicates, I would:

- Allow minor corrections (as suggested by @qgroom)
- Check for duplicate taxonIDs and append `:1`, `:2` for those

**Comment by qgroom** [comment]
OK 4 Me 2
