### ISSUE TITLE
license, rightsHolder and institutionCode

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/rinse-registry-checklist#9]
The Neobiota paper is published under the CC BY 4.0 license (https://neobiota.pensoft.net/article/4007/list/8/)

With respect to the data in supplementary material I found the following:
> This dataset is made available under the Open Database License (http://opendatacommons.org/licenses/odbl/1.0/). The Open Database License (ODbL) is a license agreement intended to allow users to freely share, modify, and use this Dataset while maintaining this same freedom for others, provided that the original source and author(s) are credited.

So use http://opendatacommons.org/licenses/odbl/1.0/ for `accessRights` and `license`?

**Comment by peterdesmet** [comment]
Leave accessRights empty. ODBL is a standard license, but not supported by GBIF. Would have to ask authors if more permissive CC0 is ok, otherwise we can use very ODBL similar CC-BY

**Comment by peterdesmet** [comment]
Also check rightsHolder `University of Cambridge`

**Comment by LienReyserhove** [comment]
Authors gave the permission to publish under the CC0. Waiting for the response for rightsholder and institutionCode

**Comment by peterdesmet** [comment]
Please indicate in the rmd that even though source data are published under ODBL, we got permissions from authors to publish under CC0.
